name: vrksh_vaatika
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.3
  geolocator: ^7.0.3
  provider: ^5.0.0
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
      - assets/map_style.txt